#!/bin/bash

# BanglaVerse Backend Environment Setup Guide
echo "🔧 BanglaVerse Backend Environment Variables Setup"
echo "=================================================="
echo ""

echo "📋 Required Environment Variables for Production:"
echo ""
echo "1. MONGODB_CONNECTION_STRING"
echo "   Description: MongoDB Atlas connection string for production database"
echo "   Example: mongodb+srv://username:password@cluster.mongodb.net/banglaverse?retryWrites=true&w=majority"
echo ""
echo "2. GOOGLE_API_KEY (or GEMINI_API_KEY)"
echo "   Description: Google Gemini API key for AI translation"
echo "   Current Value: AIzaSyAM4RqYn3o4ZIBKp4bx6J7darmCdfp17AM"
echo "   Get from: https://aistudio.google.com/"
echo ""
echo "3. NODE_ENV"
echo "   Description: Node environment"
echo "   Value: production"
echo ""
echo "4. CORS_ORIGIN"
echo "   Description: Allowed CORS origins"
echo "   Value: https://banglaverse.vercel.app,https://banglaverse.netlify.app"
echo ""

echo "🚀 How to set these in Vercel:"
echo ""
echo "Option 1: Using Vercel CLI"
echo "------------------------"
echo "vercel env add MONGODB_CONNECTION_STRING"
echo "vercel env add GOOGLE_API_KEY"
echo "vercel env add NODE_ENV"
echo "vercel env add CORS_ORIGIN"
echo ""

echo "Option 2: Using Vercel Dashboard"
echo "-------------------------------"
echo "1. Go to: https://vercel.com/dashboard"
echo "2. Find your project: banglaverse-backend-api"
echo "3. Go to Settings > Environment Variables"
echo "4. Add each variable for Production environment"
echo ""

echo "🔗 Backend URLs:"
echo "----------------"
echo "Primary: https://banglaverse-backend-api.vercel.app"
echo "Alternative: https://banglaverse-backend-lwkwp0u8c-raihanulislam12s-projects.vercel.app"
echo ""

echo "💡 Next Steps:"
echo "--------------"
echo "1. Set up MongoDB Atlas database (if not already done)"
echo "2. Add all environment variables to Vercel"
echo "3. Redeploy or wait for automatic redeployment"
echo "4. Test the API endpoints"
echo ""

echo "🧪 Test Commands (after env setup):"
echo "------------------------------------"
echo "curl https://banglaverse-backend-api.vercel.app"
echo "curl https://banglaverse-backend-api.vercel.app/health"
echo "curl https://banglaverse-backend-api.vercel.app/api-docs"
